Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	trim_reads_pe
	2

[Sat Sep  5 23:48:51 2020]
rule trim_reads_pe:
    input: /tier4/DSC/GATK/ehlim/gatk_germline_pipeline/resources/samples/BRCA_NA12892_R1.fastq.gz, /tier4/DSC/GATK/ehlim/gatk_germline_pipeline/resources/samples/BRCA_NA12892_R2.fastq.gz
    output: trimmed/BRCA_NA12892.1.fastq.gz, trimmed/BRCA_NA12892.2.fastq.gz, trimmed/BRCA_NA12892.1.unpaired.fastq.gz, trimmed/BRCA_NA12892.2.unpaired.fastq.gz
    log: logs/trimmomatic/BRCA_NA12892.log
    jobid: 1
    wildcards: sample=BRCA_NA12892

[Sat Sep  5 23:48:55 2020]
Error in rule trim_reads_pe:
    jobid: 1
    output: trimmed/BRCA_NA12892.1.fastq.gz, trimmed/BRCA_NA12892.2.fastq.gz, trimmed/BRCA_NA12892.1.unpaired.fastq.gz, trimmed/BRCA_NA12892.2.unpaired.fastq.gz
    log: logs/trimmomatic/BRCA_NA12892.log

RuleException:
WorkflowError in line 15 of /tier4/DSC/GATK/ehlim/gatk_germline_pipeline/workflow/rules/mapping.snake:
HTTPError: HTTP Error 404: Not Found
  File "/tier4/DSC/GATK/ehlim/gatk_germline_pipeline/workflow/rules/mapping.snake", line 15, in __rule_trim_reads_pe
  File "/home/ehlim/tools/miniconda3/envs/gatk/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /tier4/DSC/GATK/ehlim/gatk_germline_pipeline/.snakemake/log/2020-09-05T234851.209186.snakemake.log
