Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	mark_duplicates
	2

[Wed Sep  9 10:47:52 2020]
rule mark_duplicates:
    input: results/mapped/BRCA_NA12892.sorted.bam
    output: results/dedup/BRCA_NA12892.dedup.bam, results/dedup/BRCA_NA12892.sortsam.bam, results/dedup/BRCA_NA12892.markdup.metrics.txt
    log: logs/picard/dedup/BRCA_NA12892.log
    jobid: 1
    wildcards: sample=BRCA_NA12892

[Wed Sep  9 10:48:04 2020]
Error in rule mark_duplicates:
    jobid: 1
    output: results/dedup/BRCA_NA12892.dedup.bam, results/dedup/BRCA_NA12892.sortsam.bam, results/dedup/BRCA_NA12892.markdup.metrics.txt
    log: logs/picard/dedup/BRCA_NA12892.log

RuleException:
CalledProcessError in line 85 of /tier4/DSC/GATK/ehlim/gatk_germline_pipeline/workflow/rules/mapping.smk:
Command ' set -euo pipefail;  gatk MarkDuplicates -I results/mapped/BRCA_NA12892.sorted.bam -O results/dedup/BRCA_NA12892.dedup.bam -M results/dedup/BRCA_NA12892.markdup.metrics.txt -REMOVE_DUPLICATES false | gatk SortSam -I results/dedup/BRCA_NA12892.dedup.bam -O results/dedup/BRCA_NA12892.sortsam.bam -SO coordinate 2> logs/picard/dedup/BRCA_NA12892.log ' returned non-zero exit status 3.
  File "/tier4/DSC/GATK/ehlim/gatk_germline_pipeline/workflow/rules/mapping.smk", line 85, in __rule_mark_duplicates
  File "/home/ehlim/tools/miniconda3/envs/gatk/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /tier4/DSC/GATK/ehlim/gatk_germline_pipeline/workflow/.snakemake/log/2020-09-09T104751.889901.snakemake.log
